### PR TITLE
Files for the RISCV model 

### PR DESCRIPTION
**Pull request by Pavani14**

### CODE REVIEW

**Comment by rafaelauler** [comment]
Hi Pavani,

Thanks for doing this. In the official repo of ArchC we stick to the LLVM coding style. That means you should configure your editor to use 2 spaces for indentation, never exceed 80 columns of text, don't use tabs (convert tabs to spaces), among other things. To easily convert your source, I recommend you to install clang-format, an LLVM utility that formats your code for you. Depending on the editor you use, you can even integrate the tool in your editor, so you can easily call clang-format for a fragment of code and indent it automatically.

For .ac files, same thing, but you can't rely on clang-format and we are less strict. So just make sure you use 2 spaces for indentation.

Can you implement this changes and update your pull request?

**Comment by Pavani14** [comment]
The codes have been transformed according to the clang format

**Comment by rafaelauler** [comment]
Thanks! You should also improve the commit messages. They can be better. For example, in your first commit it should read something along the lines of "Initial model with untested instructions". If you wish to add a more detailed message, you are welcome to do so by appending two newlines and adding a longer description (remember the tips I gave about how to write commit messages).

For the subsequent commits, it would be better if it indicates which files are being changed, for example "Formatted risv_isa.cpp according to clang-format [NFC]", so we can easily tell the different between one commit and another one. Notice the "NFC". I would suggest you to use the [NFC] tag (no functionality change) in commits that are purely refactoring and do not introduce new functionalities in the model. In this way, we can easily keep track of which commits are supposed to preserve the behaviour of the simulator exactly in the same way as before and keeps it easy to bisect problems (that is, to skip this commit if we are looking for which commit broke something). If you are not sure the exact same behaviour is preserved, you can use NFCI (no functionality change intended), meaning you didn't intend to change the model (just refactor it), but may have changed it (introduced a bug) that should be considered by other developers when bisecting problems.

**Comment by raulbehl** [comment]
Hi, I tried to make the RISCV model but it fails with some errors - [http://pastebin.com/GavG4QBr]() 
I just did "acsim riscv.ac" followed by "make". The former command worked fine but "make" gave some errors. I tested on the following version of the RV32IB branch - 66b785f6588001fe8dbcd38df71d3e8bc9770e43 (latest commit).
Let me know if I am missing something here. Thanks!

**Comment by rafaelauler** [comment]
Hi Raul, to solve your error, you can either use the newest ArchC in repos (which merged this pull request https://github.com/ArchC/ArchC/pull/24 solving this issue) or you must use the "-abi" flag. Example:

`acsim risv.ac -abi`   (instead of just acsim risv.ac)

**Comment by raulbehl** [comment]
It seems to work with the -abi option. Thanks!

EDIT - Also, the model works well on the latest ArchC master.

**Comment by rafaelauler** [comment]
Pavani, do you plan to make the requested modifications? (change the commit messages)

**Comment by Pavani14** [comment]
Hi,
Sorry I missed the mail reminding me to change the commit messages. Once committed, can I still edit the commit messages? If yes, then can you explain. And if no then should I commit the same file again with different commit messages?

**Comment by rafaelauler** [comment]
Hi Pavani,

Take a look at this tutorial about rewriting your commits: https://www.atlassian.com/git/tutorials/rewriting-history

It's good to get familiar with concepts such as rebasing for your local work because frequently you'll be working with a version that depends on earlier commits being reviewed. If those commits being reviewed need to be changed, you'll need to amend them and then go to your most recent work and rebase it, so your newest commits will correctly follow the amended commits instead of the old ones. Take a time to practice this with some dummy local project so you get the feeling. This is important to allow you to work on new commits while your older commits are reviewed and needs to be changed.

The way I do this to make it easier is to put every commit under review (a patch) in a separate branch, and then create follow-up branches that depend on this to continue my work. As my base branch needs to be updated, I amend it, updating the branch, then go to succeeding branches that depend on this base branch and issue a git rebase. Git will detect the base branch has changed and will perform the rebase, solving any conflicts that may appear in the process (sometimes with need of manual intervention).

**Comment by Pavani14** [comment]
I am still learning to do the above. So as of now I am closing this pull request and issuing another one.

**Pull request closed without merging**
